backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-copy-from-front = false;
shadow = false;
fading = false;
inactive-dim = 0;
detect-transient = true;
detect-client-leader = true;
mark-wmwin-focused = true;
